
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.SQLException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Pathak
 */
public class SignUp extends javax.swing.JFrame {

    /**
     * Creates new form SignUp
     */
    private Connection connection = null;
    private PreparedStatement pst = null;
    private ResultSet resultSet = null;

    public SignUp() throws Exception {
        initComponents();
        init();
        connection = javaDbConnect.dbConnect();

    }

    public void init() {
        setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        setResizable(false);
    }

    public void close() {
        WindowEvent winClosingEvnt = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvnt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        FirstName = new javax.swing.JTextField();
        LastName = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Phn = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        Gen = new javax.swing.JComboBox<>();
        City = new javax.swing.JComboBox<>();
        btnsub = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(591, 522));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("FIRST NAME");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 40, 104, 39);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setText("LAST NAME");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 100, 104, 36);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setText("E-MAIL ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 150, 104, 31);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setText("PASSWORD");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 200, 104, 33);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setText("GENDER");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 250, 104, 31);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setText("CITY");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 300, 104, 31);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setText("PHONE");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(300, 350, 104, 28);

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 29)); // NOI18N
        jLabel8.setText("SIGN UP");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(170, 0, 149, 46);

        FirstName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        FirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameActionPerformed(evt);
            }
        });
        getContentPane().add(FirstName);
        FirstName.setBounds(410, 40, 140, 39);

        LastName.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(LastName);
        LastName.setBounds(410, 100, 140, 36);

        Email.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        getContentPane().add(Email);
        Email.setBounds(410, 150, 140, 31);

        Phn.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Phn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PhnActionPerformed(evt);
            }
        });
        getContentPane().add(Phn);
        Phn.setBounds(410, 350, 142, 28);

        jPasswordField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(410, 200, 140, 33);

        Gen.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Gen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Gen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenActionPerformed(evt);
            }
        });
        getContentPane().add(Gen);
        Gen.setBounds(410, 250, 140, 33);

        City.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        City.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jabalpur", "Katni", "Indore", "Pune", "Mumbai", "Delhi", " " }));
        getContentPane().add(City);
        City.setBounds(410, 300, 140, 31);

        btnsub.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btnsub.setText("SUBMIT");
        btnsub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsubActionPerformed(evt);
            }
        });
        getContentPane().add(btnsub);
        btnsub.setBounds(360, 420, 94, 35);

        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/back.png"))); // NOI18N
        btnback.setText("BACK");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });
        getContentPane().add(btnback);
        btnback.setBounds(0, 0, 81, 32);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/s7.jpg"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 610, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameActionPerformed

    private void GenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void PhnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PhnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PhnActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed

        close();
        Login obj = null;
        try {
            obj = new Login();
        } catch (Exception ex) {
            Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
        }
        obj.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnsubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsubActionPerformed

        
       String sql = "insert into Sign_up ((First_name,Last_name,Email,Password,Gender,City,Phone ) values (?,?,?,?,?,?,?))";
        try {
            pst = connection.prepareStatement(sql);
            pst.setString(1, FirstName.getText());
            pst.setString(2, LastName.getText());
            pst.setString(3, Email.getText());
            pst.setString(4, jPasswordField1.getText());
            pst.setString(5, (String) Gen.getSelectedItem());
            pst.setString(6, (String) City.getSelectedItem());
            pst.setString(7, Phn.getText());
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Profile Created");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);

       }
    }//GEN-LAST:event_btnsubActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new SignUp().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(SignUp.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> City;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FirstName;
    private javax.swing.JComboBox<String> Gen;
    private javax.swing.JTextField LastName;
    private javax.swing.JTextField Phn;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnsub;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
